services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blogappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

